service: simple-tracking

plugins:
  - serverless-python-requirements
  - serverless-stage-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stages:
    - dev
    - stage
    - prod

package:
  exclude:
    - .git/**
    - node_modules/**
    - venv/**
    - __pycache__/**
    - requirements.txt
    - package-lock.json
    - package.json
    - README.md

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  stage: ${opt:stage,'dev'}

functions:
  rule_create:
    handler: src/functions/rule/create._rule_create
    name: ${self:provider.stage}-ruleCreate
    description: Description of what the lambda function does
    runtime: python3.6
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    tracing: PassThrough

  rule_delete:
    handler: src/functions/rule/delete.delete
    name: ${self:provider.stage}-ruleDelete
    description: Description of what the lambda function does
    runtime: python3.6
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    tracing: PassThrough

  rule_get_by_id:
    handler: src/functions/rule/get_by_id.get_by_id
    name: ${self:provider.stage}-ruleGetById
    description: Description of what the lambda function does
    runtime: python3.6
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    tracing: PassThrough

  queue_push:
    handler: src/functions/queue/push.push
    name: ${self:provider.stage}-queuePush
    description: Description of what the lambda function does
    runtime: python3.6
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    tracing: PassThrough

  scraping_run:
    handler: src/functions/scraping/run.run
    name: ${self:provider.stage}-scrapingRun
    description: Description of what the lambda function does
    runtime: python3.6
    memorySize: 512
    timeout: 10
    reservedConcurrency: 5
    tracing: PassThrough